---
- name: Add gitlab-runner to docker group
  user:
    name: gitlab-runner
    groups: docker
    append: true

- name: Log in to Docker Registry
  docker_login:
    username: "{{ gpii_ci_worker_docker_username | mandatory }}"
    password: "{{ gpii_ci_worker_docker_password | mandatory }}"
    email: "{{ gpii_ci_worker_docker_email | mandatory }}"
  become: true
  become_user: gitlab-runner
  when: gpii_ci_worker_docker_username is defined

- name: Configure git user.name for gitlab-runner
  git_config:
    name: user.name
    scope: global
    value: GPII Bot
  become: true
  become_user: gitlab-runner

- name: Configure git user.email for gitlab-runner
  git_config:
    name: user.email
    scope: global
    value: gpii-bot@gpii.net
  become: true
  become_user: gitlab-runner

- name: Create .ssh/
  file:
    path: /home/gitlab-runner/.ssh
    state: directory
    owner: gitlab-runner
    group: gitlab-runner
    mode: 0700

- name: Configure .ssh/known_hosts
  copy:
    src: files/ssh_known_hosts
    dest: ~gitlab-runner/.ssh/known_hosts
    owner: gitlab-runner
    group: gitlab-runner
    mode: 0644
    backup: yes

- name: Configure .ssh/config
  copy:
    src: files/ssh_config
    dest: ~gitlab-runner/.ssh/config
    owner: gitlab-runner
    group: gitlab-runner
    mode: 0644
