---
- name: Install unzip
  package:
    name: unzip
    state: latest
  tags:
    - skip_ansible_lint  # latest

- name: Download terraform
  get_url:
    url: 'https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip'
    dest: /usr/local/bin/
    mode: 0555
    checksum: '{{ terraform_checksum }}'

- name: Unzip and install terraform
  unarchive:
    src: /usr/local/bin/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /usr/local/bin/
    remote_src: True

- name: Download and install terragrunt
  get_url:
    url: 'https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terragrunt_version }}/terragrunt_linux_amd64'
    dest: /usr/local/bin/terragrunt
    mode: 0555

- name: Download and install jq
  get_url:
    url: 'https://github.com/stedolan/jq/releases/download/jq-{{ jq_version }}/jq-linux64'
    dest: /usr/local/bin/jq
    mode: 0555

- name: Check for rvm gpg key
  command: gpg --list-keys
  register: gpg_list_keys
  changed_when: false

- name: Import rvm gpg key
  # Based on install instructions from https://rvm.io/
  command: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  become: true
  become_user: gitlab-runner
  when: gpg_list_keys.stdout.find('Michal Papis (RVM signing) <mpapis@gmail.com>') != -1


#- name: Install rvm
#- name: Install ruby
#- name: Install bundler
